/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'Project' 
 * Target:  'McuSTUDIO_F470VET6' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

#endif /* PRE_INCLUDE_GLOBAL_H */
